"""empty message

Revision ID: 0dcc53475dc6
Revises: 37cf0f380978
Create Date: 2022-07-16 22:42:44.136418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dcc53475dc6'
down_revision = '37cf0f380978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('confirmed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('email_confirmed_at')

    # ### end Alembic commands ###
