"""initial migration

Revision ID: 1154f98c1f63
Revises: d920ce6da4fc
Create Date: 2021-09-19 00:42:54.193068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1154f98c1f63'
down_revision = 'd920ce6da4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searched_pairs', sa.Column('existing_pairs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searched_pairs', 'existing_pairs')
    # ### end Alembic commands ###
