"""empty message

Revision ID: 3c5d6495671f
Revises: f7c1706dbd09
Create Date: 2022-07-26 10:28:38.084995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5d6495671f'
down_revision = 'f7c1706dbd09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.String(), server_default='Alma Manley', nullable=False))

    with op.batch_alter_table('permaimages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.String(), server_default='Alma Manley', nullable=False))

    with op.batch_alter_table('searched_pairs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_searched', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searched_pairs', schema=None) as batch_op:
        batch_op.drop_column('last_searched')

    with op.batch_alter_table('permaimages', schema=None) as batch_op:
        batch_op.drop_column('artist')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('artist')

    # ### end Alembic commands ###
