"""empty message

Revision ID: 524b72a8da19
Revises: f5ef1d0499d9
Create Date: 2022-05-26 19:26:42.647266

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '524b72a8da19'
down_revision = 'f5ef1d0499d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('title_en', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(length=2000), nullable=True),
    sa.Column('text_en', sa.Text(length=2000), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
