"""empty message

Revision ID: 6409bfb8f76d
Revises: 0dcc53475dc6
Create Date: 2022-07-24 13:35:16.125142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6409bfb8f76d'
down_revision = '0dcc53475dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permaimages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name_da', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('display_name_en', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permaimages', schema=None) as batch_op:
        batch_op.drop_column('display_name_en')
        batch_op.drop_column('display_name_da')

    # ### end Alembic commands ###
