"""empty message

Revision ID: 6a5bf2c3373b
Revises: 85390ec3e48f
Create Date: 2022-08-11 21:45:22.175497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5bf2c3373b'
down_revision = '85390ec3e48f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairs', schema=None) as batch_op:
        batch_op.drop_column('img_count')

    # ### end Alembic commands ###
