"""empty message

Revision ID: 9ae394f41bc4
Revises: c0a3dba6741d
Create Date: 2022-07-26 10:55:03.566021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = '9ae394f41bc4'
down_revision = 'c0a3dba6741d'
branch_labels = None
depends_on = None



def upgrade():

    with op.batch_alter_table('searched_pairs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_searched', sa.DateTime(timezone=True), server_default=func.current_timestamp(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searched_pairs', schema=None) as batch_op:
        batch_op.drop_column('last_searched')

    # ### end Alembic commands ###
