"""empty message

Revision ID: 9c50780cd4f9
Revises: 
Create Date: 2021-07-09 18:06:02.093664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c50780cd4f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userimages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullpath', sa.String(), nullable=False),
    sa.Column('staticpath', sa.String(), nullable=False),
    sa.Column('userid', sa.String(), nullable=False),
    sa.Column('wordid', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('cropped', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['wordid'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fullpath'),
    sa.UniqueConstraint('staticpath')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userimages')
    # ### end Alembic commands ###
