"""empty message

Revision ID: c0a3dba6741d
Revises: 3c5d6495671f
Create Date: 2022-07-26 10:31:13.956347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = 'c0a3dba6741d'
down_revision = '3c5d6495671f'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('searched_pairs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_searched', sa.DateTime(timezone=True)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searched_pairs', schema=None) as batch_op:
        batch_op.drop_column('last_searched')

    # ### end Alembic commands ###
