"""empty message

Revision ID: ccb99b0dc2f9
Revises: 6a5bf2c3373b
Create Date: 2022-08-11 22:18:36.341901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb99b0dc2f9'
down_revision = '6a5bf2c3373b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairs', schema=None) as batch_op:
        batch_op.drop_column('word_sound')
        batch_op.drop_column('partner_sound')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_sound', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('word_sound', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
