"""empty message

Revision ID: d920ce6da4fc
Revises: 
Create Date: 2021-07-14 13:47:33.003581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd920ce6da4fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('userimages') as op_batch:
        # ### commands auto generated by Alembic - please adjust! ###
        op_batch.drop_column('cropped')
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userimages', sa.Column(
        'cropped', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
