"""empty message

Revision ID: f57438cba477
Revises: 7baf30b80e46
Create Date: 2021-09-19 21:46:16.417782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57438cba477'
down_revision = '7baf30b80e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('times_used', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'times_used')
    # ### end Alembic commands ###
