"""empty message

Revision ID: f7c1706dbd09
Revises: 6409bfb8f76d
Create Date: 2022-07-24 13:38:13.774784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c1706dbd09'
down_revision = '6409bfb8f76d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permaimages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permaimages', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
